### ISSUE TITLE
Faster Hash

### ISSUE THREAD

**Issue by AmarRSingh** [AmarRSingh/MoloChameleon#7]
Replace the Substrate hash function with FNV1-hash (non-cryptographic hash function) for performance benefits. This module only uses the hash function for uid generation so it is appropriate to consider non-cryptographic, high-performance hash functions.

**Comment by AmarRSingh** [comment]
LOL I'm not even using a hash function for this iteration. Encoding a subset of the proposal as a `Vec<u8>` provides enough uniqueness...

**Comment by 4meta5** [comment]
Closed because this was a **premature optimization**
